### ISSUE TITLE
android 魅族 note2 真机运行不可以，模拟器上运行可以

### ISSUE THREAD

**Issue by LuoboDcom** [zhongjie-chen/rn_rank#10]
我在魅族note2上运行后，直接闪退。（抱歉我不知道在哪里看报错信息，至少DOS终端上是没有的）。手机信息 ： m2 note , Android 5.1

**Comment by zhongjie-chen** [comment]
http://apk.gfan.com/Product/App1099977.html 市场上下载在魅蓝note2上有问题吗，  你可以试着更新下RN版本

**Comment by LuoboDcom** [comment]
@zhongjie-chen 好的，我试下，谢谢
