### ISSUE TITLE
“react-native start ” 运行失败

### ISSUE THREAD

**Issue by youstrive** [zhongjie-chen/rn_rank#4]
Administrator@LS--20150607OKS MINGW32 /e/trump_tmp/rn_rank (master)
$ react-native start
Command `start` unrecognized. Did you mean to run this inside a react-native project?

**Comment by zhongjie-chen** [comment]
install了吗

**Comment by youstrive** [comment]
install 了，我是从第一步开始执行的，都执行成功了。我今天试试在ubuntu系统下能不能行

**Comment by youstrive** [comment]
ubuntu下直接挂了

ubuntu@ubuntu:~/test_trump$ npm install -g react-native-cli
npm http GET https://registry.npmjs.org/react-native-cli

npm ERR! Error: failed to fetch from registry: react-native-cli
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/youyungong/test_trump/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.8.0-29-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "react-native-cli"
npm ERR! cwd /home/youyungong/test_trump
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: react-native-cli
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/youyungong/test_trump/npm-debug.log
npm not ok

**Comment by zhongjie-chen** [comment]
liunx系统我没测试过 应该是环境问题

**Comment by youstrive** [comment]
是我npm 版本太低造成的，现在可以react-native start，但是还是报错了

ubuntu@ubuntu:~/test_trump/rn_rank$ react-native start
/home/ubuntu/test_trump/rn_rank/node_modules/react-native/local-cli/cli.js:122
class CreateSuppressingTerminalAdapter extends TerminalAdapter {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ubuntu/test_trump/rn_rank/node_modules/react-native/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/test_trump/rn_rank/node_modules/react-native/cli.js:15:18)
    at Module._compile (module.js:460:26)

**Comment by liuhuawen** [comment]
/Users/guest/workspace/rn_rank/rn_rank/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:494:3: error: ignoring return value of function declared with
      warn_unused_result attribute [-Werror,-Wunused-result]
  SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);
  ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/guest/workspace/rn_rank/rn_rank/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1334:5: error: ignoring return value of function declared with
      warn_unused_result attribute [-Werror,-Wunused-result]
    SecRandomCopyBytes(kSecRandomDefault, sizeof(uint32_t), (uint8_t *)mask_key);
    ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

** BUILD FAILED **
运行的时候报这个错，是什么问题？
