### ISSUE TITLE
Congratulation！

### ISSUE THREAD

**Issue by Richard-Cao** [zhongjie-chen/rn_rank#9]

**Comment by LuoboDcom** [comment]
@Richard-Cao  我clone下项目后，直接 react-native run-android 提示 
Command `run-android` unrecognized. Did you mean to run this inside a react-native project?
我应该怎么运行呢

**Comment by LuoboDcom** [comment]
@zhongjie-chen  我clone下项目后，直接 react-native run-android 提示 
Command run-android unrecognized. Did you mean to run this inside a react-native project?
我应该怎么运行呢

**Comment by LuoboDcom** [comment]
@Richard-Cao  @zhongjie-chen  抱歉，之前没有看到下面的提示。谢谢开源这么好的项目！

**Comment by zhongjie-chen** [comment]
@Richard-Cao 感谢 reading ：）

**Comment by Richard-Cao** [comment]
加油！ @zhongjie-chen

**Comment by Richard-Cao** [comment]
@LuoboDcom 你应该要先npm install才可以
